// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/enterprise"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// EnterpriseUpdate is the builder for updating Enterprise entities.
type EnterpriseUpdate struct {
	config
	hooks    []Hook
	mutation *EnterpriseMutation
}

// Where appends a list predicates to the EnterpriseUpdate builder.
func (_u *EnterpriseUpdate) Where(ps ...predicate.Enterprise) *EnterpriseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnterpriseUpdate) SetUpdatedAt(v time.Time) *EnterpriseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EnterpriseUpdate) SetDeletedAt(v time.Time) *EnterpriseUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableDeletedAt(v *time.Time) *EnterpriseUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EnterpriseUpdate) ClearDeletedAt() *EnterpriseUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *EnterpriseUpdate) SetName(v string) *EnterpriseUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableName(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *EnterpriseUpdate) SetNotes(v string) *EnterpriseUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableNotes(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *EnterpriseUpdate) ClearNotes() *EnterpriseUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnterpriseUpdate) SetStatus(v string) *EnterpriseUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnterpriseUpdate) SetNillableStatus(v *string) *EnterpriseUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *EnterpriseUpdate) AddAccountIDs(ids ...int64) *EnterpriseUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *EnterpriseUpdate) AddAccounts(v ...*Account) *EnterpriseUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the EnterpriseMutation object of the builder.
func (_u *EnterpriseUpdate) Mutation() *EnterpriseMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *EnterpriseUpdate) ClearAccounts() *EnterpriseUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *EnterpriseUpdate) RemoveAccountIDs(ids ...int64) *EnterpriseUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *EnterpriseUpdate) RemoveAccounts(v ...*Account) *EnterpriseUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnterpriseUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnterpriseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnterpriseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnterpriseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnterpriseUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if enterprise.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprise.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := enterprise.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnterpriseUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := enterprise.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := enterprise.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Enterprise.status": %w`, err)}
		}
	}
	return nil
}

func (_u *EnterpriseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enterprise.Table, enterprise.Columns, sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprise.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(enterprise.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(enterprise.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(enterprise.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(enterprise.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(enterprise.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enterprise.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   enterprise.AccountsTable,
			Columns: []string{enterprise.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   enterprise.AccountsTable,
			Columns: []string{enterprise.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   enterprise.AccountsTable,
			Columns: []string{enterprise.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enterprise.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnterpriseUpdateOne is the builder for updating a single Enterprise entity.
type EnterpriseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnterpriseMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnterpriseUpdateOne) SetUpdatedAt(v time.Time) *EnterpriseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *EnterpriseUpdateOne) SetDeletedAt(v time.Time) *EnterpriseUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableDeletedAt(v *time.Time) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *EnterpriseUpdateOne) ClearDeletedAt() *EnterpriseUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *EnterpriseUpdateOne) SetName(v string) *EnterpriseUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableName(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *EnterpriseUpdateOne) SetNotes(v string) *EnterpriseUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableNotes(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *EnterpriseUpdateOne) ClearNotes() *EnterpriseUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetStatus sets the "status" field.
func (_u *EnterpriseUpdateOne) SetStatus(v string) *EnterpriseUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *EnterpriseUpdateOne) SetNillableStatus(v *string) *EnterpriseUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *EnterpriseUpdateOne) AddAccountIDs(ids ...int64) *EnterpriseUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *EnterpriseUpdateOne) AddAccounts(v ...*Account) *EnterpriseUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the EnterpriseMutation object of the builder.
func (_u *EnterpriseUpdateOne) Mutation() *EnterpriseMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *EnterpriseUpdateOne) ClearAccounts() *EnterpriseUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *EnterpriseUpdateOne) RemoveAccountIDs(ids ...int64) *EnterpriseUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *EnterpriseUpdateOne) RemoveAccounts(v ...*Account) *EnterpriseUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Where appends a list predicates to the EnterpriseUpdate builder.
func (_u *EnterpriseUpdateOne) Where(ps ...predicate.Enterprise) *EnterpriseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnterpriseUpdateOne) Select(field string, fields ...string) *EnterpriseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Enterprise entity.
func (_u *EnterpriseUpdateOne) Save(ctx context.Context) (*Enterprise, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnterpriseUpdateOne) SaveX(ctx context.Context) *Enterprise {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnterpriseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnterpriseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnterpriseUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if enterprise.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprise.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := enterprise.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnterpriseUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := enterprise.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := enterprise.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Enterprise.status": %w`, err)}
		}
	}
	return nil
}

func (_u *EnterpriseUpdateOne) sqlSave(ctx context.Context) (_node *Enterprise, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enterprise.Table, enterprise.Columns, sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Enterprise.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enterprise.FieldID)
		for _, f := range fields {
			if !enterprise.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != enterprise.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprise.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(enterprise.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(enterprise.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(enterprise.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(enterprise.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(enterprise.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enterprise.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   enterprise.AccountsTable,
			Columns: []string{enterprise.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   enterprise.AccountsTable,
			Columns: []string{enterprise.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   enterprise.AccountsTable,
			Columns: []string{enterprise.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Enterprise{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enterprise.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
