// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/enterprise"
)

// EnterpriseCreate is the builder for creating a Enterprise entity.
type EnterpriseCreate struct {
	config
	mutation *EnterpriseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *EnterpriseCreate) SetCreatedAt(v time.Time) *EnterpriseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableCreatedAt(v *time.Time) *EnterpriseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EnterpriseCreate) SetUpdatedAt(v time.Time) *EnterpriseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableUpdatedAt(v *time.Time) *EnterpriseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *EnterpriseCreate) SetDeletedAt(v time.Time) *EnterpriseCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableDeletedAt(v *time.Time) *EnterpriseCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *EnterpriseCreate) SetName(v string) *EnterpriseCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *EnterpriseCreate) SetNotes(v string) *EnterpriseCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableNotes(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EnterpriseCreate) SetStatus(v string) *EnterpriseCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EnterpriseCreate) SetNillableStatus(v *string) *EnterpriseCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *EnterpriseCreate) AddAccountIDs(ids ...int64) *EnterpriseCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *EnterpriseCreate) AddAccounts(v ...*Account) *EnterpriseCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// Mutation returns the EnterpriseMutation object of the builder.
func (_c *EnterpriseCreate) Mutation() *EnterpriseMutation {
	return _c.mutation
}

// Save creates the Enterprise in the database.
func (_c *EnterpriseCreate) Save(ctx context.Context) (*Enterprise, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EnterpriseCreate) SaveX(ctx context.Context) *Enterprise {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EnterpriseCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if enterprise.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprise.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := enterprise.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if enterprise.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized enterprise.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := enterprise.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := enterprise.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EnterpriseCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Enterprise.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Enterprise.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Enterprise.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := enterprise.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Enterprise.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Enterprise.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := enterprise.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Enterprise.status": %w`, err)}
		}
	}
	return nil
}

func (_c *EnterpriseCreate) sqlSave(ctx context.Context) (*Enterprise, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EnterpriseCreate) createSpec() (*Enterprise, *sqlgraph.CreateSpec) {
	var (
		_node = &Enterprise{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(enterprise.Table, sqlgraph.NewFieldSpec(enterprise.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(enterprise.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(enterprise.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(enterprise.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(enterprise.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(enterprise.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(enterprise.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   enterprise.AccountsTable,
			Columns: []string{enterprise.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Enterprise.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseCreate) OnConflict(opts ...sql.ConflictOption) *EnterpriseUpsertOne {
	_c.conflict = opts
	return &EnterpriseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseCreate) OnConflictColumns(columns ...string) *EnterpriseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseUpsertOne{
		create: _c,
	}
}

type (
	// EnterpriseUpsertOne is the builder for "upsert"-ing
	//  one Enterprise node.
	EnterpriseUpsertOne struct {
		create *EnterpriseCreate
	}

	// EnterpriseUpsert is the "OnConflict" setter.
	EnterpriseUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseUpsert) SetUpdatedAt(v time.Time) *EnterpriseUpsert {
	u.Set(enterprise.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateUpdatedAt() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnterpriseUpsert) SetDeletedAt(v time.Time) *EnterpriseUpsert {
	u.Set(enterprise.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateDeletedAt() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnterpriseUpsert) ClearDeletedAt() *EnterpriseUpsert {
	u.SetNull(enterprise.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *EnterpriseUpsert) SetName(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateName() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldName)
	return u
}

// SetNotes sets the "notes" field.
func (u *EnterpriseUpsert) SetNotes(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateNotes() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *EnterpriseUpsert) ClearNotes() *EnterpriseUpsert {
	u.SetNull(enterprise.FieldNotes)
	return u
}

// SetStatus sets the "status" field.
func (u *EnterpriseUpsert) SetStatus(v string) *EnterpriseUpsert {
	u.Set(enterprise.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseUpsert) UpdateStatus() *EnterpriseUpsert {
	u.SetExcluded(enterprise.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseUpsertOne) UpdateNewValues() *EnterpriseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(enterprise.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EnterpriseUpsertOne) Ignore() *EnterpriseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseUpsertOne) DoNothing() *EnterpriseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseCreate.OnConflict
// documentation for more info.
func (u *EnterpriseUpsertOne) Update(set func(*EnterpriseUpsert)) *EnterpriseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseUpsertOne) SetUpdatedAt(v time.Time) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateUpdatedAt() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnterpriseUpsertOne) SetDeletedAt(v time.Time) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateDeletedAt() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnterpriseUpsertOne) ClearDeletedAt() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *EnterpriseUpsertOne) SetName(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateName() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateName()
	})
}

// SetNotes sets the "notes" field.
func (u *EnterpriseUpsertOne) SetNotes(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateNotes() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *EnterpriseUpsertOne) ClearNotes() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearNotes()
	})
}

// SetStatus sets the "status" field.
func (u *EnterpriseUpsertOne) SetStatus(v string) *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseUpsertOne) UpdateStatus() *EnterpriseUpsertOne {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *EnterpriseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EnterpriseUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EnterpriseUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EnterpriseCreateBulk is the builder for creating many Enterprise entities in bulk.
type EnterpriseCreateBulk struct {
	config
	err      error
	builders []*EnterpriseCreate
	conflict []sql.ConflictOption
}

// Save creates the Enterprise entities in the database.
func (_c *EnterpriseCreateBulk) Save(ctx context.Context) ([]*Enterprise, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Enterprise, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EnterpriseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EnterpriseCreateBulk) SaveX(ctx context.Context) []*Enterprise {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EnterpriseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EnterpriseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Enterprise.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EnterpriseUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *EnterpriseCreateBulk) OnConflict(opts ...sql.ConflictOption) *EnterpriseUpsertBulk {
	_c.conflict = opts
	return &EnterpriseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EnterpriseCreateBulk) OnConflictColumns(columns ...string) *EnterpriseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EnterpriseUpsertBulk{
		create: _c,
	}
}

// EnterpriseUpsertBulk is the builder for "upsert"-ing
// a bulk of Enterprise nodes.
type EnterpriseUpsertBulk struct {
	create *EnterpriseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EnterpriseUpsertBulk) UpdateNewValues() *EnterpriseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(enterprise.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Enterprise.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EnterpriseUpsertBulk) Ignore() *EnterpriseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EnterpriseUpsertBulk) DoNothing() *EnterpriseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EnterpriseCreateBulk.OnConflict
// documentation for more info.
func (u *EnterpriseUpsertBulk) Update(set func(*EnterpriseUpsert)) *EnterpriseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EnterpriseUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EnterpriseUpsertBulk) SetUpdatedAt(v time.Time) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateUpdatedAt() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EnterpriseUpsertBulk) SetDeletedAt(v time.Time) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateDeletedAt() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EnterpriseUpsertBulk) ClearDeletedAt() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *EnterpriseUpsertBulk) SetName(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateName() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateName()
	})
}

// SetNotes sets the "notes" field.
func (u *EnterpriseUpsertBulk) SetNotes(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateNotes() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *EnterpriseUpsertBulk) ClearNotes() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.ClearNotes()
	})
}

// SetStatus sets the "status" field.
func (u *EnterpriseUpsertBulk) SetStatus(v string) *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *EnterpriseUpsertBulk) UpdateStatus() *EnterpriseUpsertBulk {
	return u.Update(func(s *EnterpriseUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *EnterpriseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EnterpriseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EnterpriseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EnterpriseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
